version: '3.3'

services:
  docker:
    restart: always
    build: 
      context: .
      dockerfile: dockerfiles/docker
    ports:
      - 0.0.0.0:2375:2375
    env_file:
      - .env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    volumes:
      - type: bind
        source: ./logs
        target: /app/src/logs
      - type: bind
        source: ./export
        target: /app/src/export

  mongodb-primary:
    restart: always
    image: docker.io/bitnami/mongodb:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DATABASE=DockerHoneypot
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    expose:
      - 27017

  mongodb-secondary:
    restart: always
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DATABASE=DockerHoneypot
    expose:
      - 27017

  mongodb-arbiter:
    restart: always
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DATABASE=DockerHoneypot
    expose:
      - 27017

volumes:
  mongodb_master_data:
    driver: local