sensor:
  id: 'sensor_default'
  log_file: true

mongodb:
  uri: ""
 
headers:
  Server: "Docker/18.05.0-ce (linux)"
  Docker-Experimental: false
  Ostype: linux

misp:
  enabled: true
  url: ''
  key: ''
  verify: False
  cert: ''